# Generated by Django 3.2.9 on 2022-03-07 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='topic',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
