# Generated by Django 3.2.9 on 2022-03-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='blogs_written',
            field=models.IntegerField(default=0),
        ),
    ]
