# Generated by Django 3.2.9 on 2022-03-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_blogs_written'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='blogs_written',
            field=models.IntegerField(default='Post.objects.filter(status="published").count()'),
        ),
    ]
