# Generated by Django 3.2.9 on 2022-02-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.TextField(default='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
